### ISSUE TITLE
coloring the svgs

### ISSUE THREAD

**Issue by uloco** [uloco/numix-cursor#4]
I looked through the `svg` files and realized, that I have made some mistakes by setting the color values to gradients in some places, rather than making flat fill colors. There is also the problem, that not every outline is defined as a stroke. In some places it is just a fill overlayed with another fill, so it is really hard to distinguish between each other. It would be a lot of work to fix this, and probably in some cases it isn't possible at all (not that easy / I don't know how)... 

The original script with just finding and replacing the hex string did work pretty well (and fast) actually, why don't we just use this one for coloring light/dark theme and the rest of the cursor? 

I do understand, that by not specifying the areas, we would break everything, if a color is changed to the same color as it is somewhere else. (For example for the light/dark theme switch, we would have to color all the white parts to another color like red, then color black to white and then color red to black.

If we permit setting the custom color (for the colored base part) to the ones already used in the default theme, there should be no problem with that. 

The actual default colors are:

| area | hex color |
| --- | --- |
| light base | `#e8e8e8` |
| colored base | `#d54933` |
| dark outline | `#2d2d2d` |
| red circle | `#cf3a3a` |
| green plus | `#59c453` |
| red minus | `#ce3838` |
| purple link | `#b77aff` |
| blue arrow | `#2aaee3` |
| question mark pink | `#f7a3f0` |

We should permit these exact colors as custom ones. The user can change his desired custom color by just one value and it will work. 
I think it is not important that really every color is supported, this is no enterprise software :smile:.

Just hardcode these colors in your script, that nobody can change them without altering the script itself. Then we would need a default folder, where the default svgs are stored and never altered. So we can start from scratch, every new coloring. (You would simply copy all svgs from the `src/defaults` folder to `src`, do all generation stuff, and move + overwrite the cursor files to `theme/Numix-Cursor/cursors/`.

Woa, this evolved to a pretty long post :smiley:

**Comment by osendott** [comment]
I just realized while laying in bed last night that I needed to work with a copy of the source files instead of the original files themselves. I'll take care of all the source/directory/.theme file stuff first, and then start in on the coloring.

**Comment by osendott** [comment]
Working with copy of files, installing complete theme at end, and edit of Orange color (with check in place) with custom color supplier by user implemented

**Comment by osendott** [comment]
I'll also add in (first thing in morning) some sort of choose light/dark base option
